export const safeUserSelect = {
  id: true,
  email: true,
  firstName: true,
  lastName: true,
  phone: true,
  role: true,
  status: true,
  gender: true,
  displayPicture: true,
  birthday: true,
  mustChangePassword: true,
  createdAt: true,
  updatedAt: true,
};
